export const tagTypes = {
  service: "service",
  service_marquee: "service_marquee",
  why_trust_us: "why-trust-us",
  auth: "auth",
  user: "user",
  brand: "brand",
  team: "team",
  our_work: "our-works",
  technology: "technology",
  capabilities: "capabilities",
  industries: "industries",
  our_product_price: "our_product_price",
  faq_category: "faq_category",
  faqs: "faqs",
  products: "products",
  product_category: "product_category",
  product_top_category: "product_top_category",
  terms_and_conditions: "terms_and_conditions",
  privacy_policy: "privacy_policy",
  hero_banner: "hero_banner",
  banners: "banners",
  testimonial: "testimonial",
  about: "about",
  blog_category: "blog_category",
  blogs: "blogs",
  assigned_technology: "assigned_technology",
};

export const tagTypesList = [
  tagTypes.service,
  tagTypes.service_marquee,
  tagTypes.auth,
  tagTypes.user,
  tagTypes.why_trust_us,
  tagTypes.brand,
  tagTypes.team,
  tagTypes.our_work,
  tagTypes.technology,
  tagTypes.capabilities,
  tagTypes.industries,
  tagTypes.our_product_price,
  tagTypes.faq_category,
  tagTypes.faqs,
  tagTypes.products,
  tagTypes.product_category,
  tagTypes.product_top_category,
  tagTypes.terms_and_conditions,
  tagTypes.privacy_policy,
  tagTypes.hero_banner,
  tagTypes.banners,
  tagTypes.testimonial,
  tagTypes.about,
  tagTypes.blog_category,
  tagTypes.blogs,
  tagTypes.assigned_technology,
];
