export const tagTypes = {
  service: "service",
  service_marquee: "service_marquee",
  why_trust_us: "why-trust-us",
  auth: "auth",
  user: "user",
  brand: "brand",
  team: "team",
  our_work: "our-works",
  technology: "technology",
  capabilities: "capabilities",
  industries: "industries",
  our_product_price: "our_product_price",
  faq_category: "faq_category",
};

export const tagTypesList = [
  tagTypes.service,
  tagTypes.service_marquee,
  tagTypes.auth,
  tagTypes.user,
  tagTypes.why_trust_us,
  tagTypes.brand,
  tagTypes.team,
  tagTypes.our_work,
  tagTypes.technology,
  tagTypes.capabilities,
  tagTypes.industries,
  tagTypes.our_product_price,
  tagTypes.faq_category,
];
